core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
)
from app.views.group import GroupEditView
from app.views.payment import PaymentEditView
from app.views.question import (
    QuestionCreateView,
    QuestionEditView,
    question_delete,
    question_list,
)

from config import *
from app.views.botwebhook import bot_webhook
from app.views.main import *
from app.views.statement import *
from app.views.statistic import *
from app.views.admin import *
from app.views.answer import *
from app.views.click_api import *
from app.views.payme_endpoint import *

urlpatterns = [
    # main
    path("xiidot1303/", admin.site.urls),
    path(TELEGRAM_BOT_API_TOKEN, bot_webhook),
    path("", main_menu, name="main_menu"),
    # auth
    path("accounts/login/", LoginView.as_view()),
    path(
        "changepassword/",
        PasswordChangeView.as_view(template_name="registration/change_password.html"),
        name="editpassword",
    ),
    path(
        "changepassword/done/",
        PasswordChangeDoneView.as_view(template_name="registration/afterchanging.html"),
        name="password_change_done",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    # get file
    path("files/<str:folder>/<str:file>/", get_photos, name="get_photo"),
    # statement
    path("statement/list", list_statements, name="statement_list"),
    path("statement/confirm/<int:pk>/", confirm_statement, name="statement_confirm"),
    path("statement/answers/<int:pk>", card, name="statement_answer"),
    path("statement/shared", shared_statements, name="statement_shared"),
    # answer
    path("answer/update/<int:pk>/", AnswerEditView.as_view(), name="answer_update"),
    path("answer/detail/<int:pk>/", AnswerDetailView.as_view(), name="answer_detail"),
    path("answer/create", AnswerCreateView.as_view(), name="answer_create"),
    # question
    path("question/create", QuestionCreateView.as_view(), name="question_create"),
    path("question/list", question_list, name="question_list"),
    path(
        "question/update/<int:pk>/", QuestionEditView.as_view(), name="question_update"
    ),
    path("question/delete/<int:pk>/", question_delete, name="question_delete"),
    # settings
    path("payment/update/<int:pk>/", PaymentEditView.as_view(), name="payment_update"),
    path("group/update/<int:pk>/", GroupEditView.as_view(), name="group_update"),
    path("profile", change_profile, name="change_profile"),
    # statistic
    path("statistic/users", bot_users, name="statistic_users"),
    # message
    path("sendMessage/<str:status>", MessageCreateView.as_view(), name="send_message"),
    # click-api
    path("click/prepare", click_prepare),
    path("click/complete", click_complete),

    # payme endpoint
    path("payme/endpoint", payme_endpoint),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
import os

from django.db import models


class BotUser(models.Model):
    user_id = models.IntegerField(null=True)
    name = models.CharField(null=True, blank=True, max_length=200)
    username = models.CharField(null=True, blank=True, max_length=200)
    firstname = models.CharField(null=True, blank=True, max_length=500)
    phone = models.CharField(null=True, blank=True, max_length=40)
    lang = models.CharField(null=True, blank=True, max_length=5)
    date = models.DateTimeField(db_index=True, null=True, auto_now_add=True, blank=True)
    is_client = models.BooleanField(blank=True, null=True)

    def __str__(self) -> str:
        try:
            return self.name + " " + str(self.phone)
        except:
            return super().__str__()


class Question(models.Model):
    questionuz = models.CharField(null=True, blank=True, max_length=500)
    questionru = models.CharField(null=True, blank=True, max_length=500)
    variantsuz = models.CharField(null=True, blank=True, max_length=300)
    variantsru = models.CharField(null=True, blank=True, max_length=300)
    index = models.IntegerField(null=True, blank=True)
    req_photo = models.BooleanField(blank=True, null=True)  # is required photo
    is_required = models.BooleanField(blank=True, null=True)  #  is required answer


class Answer(models.Model):
    user = models.ForeignKey(
        "app.BotUser", null=True, blank=False, on_delete=models.PROTECT
    )
    questions = models.CharField(
        null=True, blank=True, max_length=3000
    )  # save questions by "/""
    date = models.DateTimeField(null=True, blank=True, max_length=20)
    answer = models.CharField(null=True, blank=True, max_length=300)
    new_answer = models.CharField(null=True, blank=True, max_length=300)
    photo = models.FileField(upload_to="photos/", null=True, blank=True)
    payment = models.FileField(upload_to="payment/", null=True, blank=True)
    text = models.TextField(blank=True, null=True, max_length=3000, default="")

    end = models.BooleanField(
        null=True, blank=True, default=False
    )  # completed answer or not

    def filename(self):
        return os.path.basename(self.photo.name)

    # def __str__(self) -> str:
    #     return self.


class Statement(models.Model):
    answer = models.ForeignKey(
        "Answer", null=True, blank=False, on_delete=models.PROTECT
    )
    status = models.CharField(
        null=True,
        blank=True,
        max_length=20,
        choices=(
            ("waiting", "waiting"),
            ("cancelled", "cancelled"),
            ("confirmed", "confirmed"),
        ),
    )
    payment_status = models.CharField(
        null=True,
        blank=True,
        max_length=20,
        choices=((0, "В ожидании"), (-1, "Отменено"), (1, "Оплачено")),
        default=0,
    )
    invoice_id = models.IntegerField(null=True, blank=True)
    views = models.IntegerField(null=True, blank=True, default=0)


class BackupQuestion(models.Model):
    user = models.ForeignKey(
        "app.BotUser", null=True, blank=False, on_delete=models.PROTECT
    )
    question = models.CharField(null=True, blank=True, max_length=500)
    variants = models.CharField(null=True, blank=True, max_length=300)
    index = models.IntegerField(null=True, blank=True)
    req_photo = models.BooleanField(blank=True, null=True)  # is required photo
    is_required = models.BooleanField(blank=True, null=True)  #  is required answer
    answer = models.IntegerField(null=True, blank=True)  # answer ID


class Group(models.Model):
    group_id = models.CharField(null=True, blank=True, max_length=30)
    name = models.CharField(null=True, blank=True, max_length=500)


class Payment(models.Model):
    textuz = models.CharField(null=True, blank=True, max_length=1000)
    textru = models.CharField(null=True, blank=True, max_length=1000)
    card = models.CharField(null=True, blank=True, max_length=50)
    amount = models.IntegerField(null=True, blank=True)


class Message(models.Model):
    users = models.ManyToManyField("app.BotUser", blank=True)
    all = models.BooleanField(blank=True, null=True)
    text = models.TextField(blank=True, null=True, max_length=1000)
    photo = models.FileField(upload_to="messages/", null=True, blank=True)

app/views/question.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView
from app.models import *
from app.forms import *


@login_required
def question_list(request):
    questions = Question.objects.all().order_by("index")
    context = {"questions": questions}
    return render(request, "question/allquestions.html", context)


class QuestionCreateView(LoginRequiredMixin, CreateView):
    template_name = "question/create_question.html"
    form_class = QuestionForm
    success_url = "/question/list"
    # success_url = '/question_detail/{id}'


class QuestionEditView(LoginRequiredMixin, UpdateView):
    model = Question
    form_class = QuestionForm
    template_name = "question/update_question.html"
    # success_url = '/question_detail/{id}'
    success_url = "/question/list"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context


@login_required
def question_delete(request, pk):
    question = Question.objects.get(pk=pk)
    question.delete()
    return redirect(question_list)

app/templates/question/allquestions.html
{% extends 'layout/basic.html' %}

{% load static %}
{% load index %}
{% load functions %}

{% block title %}
Все вопросы 
{% endblock %}

{% block main %}

<a href="{% url 'question_create' %}">
   <button type="button" class="btn btn-outline-dark rounded-pill mt-2" style="margin-bottom: 20px;"><i class="ri-heart-line"></i>Добавить</button>

</a>

<table class="table">
    <thead>
       <tr>
          <th scope="col">№</th>
          <th scope="col">Вопросы (русс.)</th>
          <th scope="col">Вопросы (узб.)</th>
          <th scope="col">Варианты (русс.)</th>
          <th scope="col">Варианты (узб.)</th>
          <th scope="col">Индекс</th>
          <th>Действия</th>
       </tr>
    </thead>
    <tbody>
        {% for q in questions %}
       <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td><button type="button" class="btn iq-bg-success mt-2" data-container="body" data-toggle="popover" data-placement="right" data-content="{{ q.questionru }}">{{ q.questionru|cuttext }}</button></td>
          <td><button type="button" class="btn iq-bg-success mt-2" data-container="body" data-toggle="popover" data-placement="right" data-content="{{ q.questionuz }}">{{ q.questionuz|cuttext }}</button></td>
          <td><button type="button" class="btn iq-bg-success mt-2" data-container="body" data-toggle="popover" data-placement="right" data-content="{{ q.variantsru }}">{{ q.variantsru|cuttext }}</button></td>
          <td><button type="button" class="btn iq-bg-success mt-2" data-container="body" data-toggle="popover" data-placement="right" data-content="{{ q.variantsuz }}">{{ q.variantsuz|cuttext }}</button></td>
          <td>{{ q.index }}</td>
          <td><a id = "a" href="{% url 'question_delete' q.pk %}" onclick="return confirm(&#39;Вы уверены?&#39;)" class="btn btn-danger rounded-pill mt-2"><i class="fas fa-trash" aria-hidden="true"></i></a>
            <a id = "a" href="{% url 'question_update' q.pk %}" class="btn btn-primary rounded-pill mt-2"><i class="fas fa-edit"></i></a></td>
       </tr>
        {% endfor %}
    </tbody>
 </table>

{% endblock %}

app/templates/question/create_question.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block title %}
Добавить вопрос
{% endblock %}

{% block main %}

<form method = "post" enctype="multipart/form-data">

    {% csrf_token %}
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label for="id_questionuz">Вопрос на Узбекском</label>
                <textarea required class="form-control" id="id_questionuz" name="questionuz" rows="3" style="width: 700px;"></textarea>
            </div>
        </div>    
        <div class="col">
            <div class="form-group">
                <label for="id_questionru">Вопрос на Русском</label>
                <textarea required class="form-control" id="id_questionru" name="questionru" rows="3" style="width: 700px;"></textarea>
            </div>
        </div>    

    </div>
    <div class="row">

        <div class="col">
            <div class="form-group">
                <label for="id_variantsuz">Варианты на Узбекском</label>
                <input type="text" id="id_variantsuz" name="variantsuz" class="form-control" placeholder="variant1//variants2//variant3">
            </div>
        </div>

        <div class="col">
            <div class="form-group">
                <label for="id_variantsru">Варианты на Русском</label>
                <input type="text" id="id_variantsru" name="variantsru" class="form-control" placeholder="variant1//variants2//variant3">
            </div>
        </div>
        
    </div>

    <div class="row">
        <div class="col">
            <div class="form-group">
                <label for="id_index">Индекс</label>
                <input required type="number" name="index" class="form-control form-control-sm" id="id_index" placeholder="порядок">
            
            </div>
        </div>
        <div class="col">
            <div class="form-group">

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <div class="custom-control custom-switch custom-control-inline">
                    <input type="checkbox" class="custom-control-input" id="id_req_photo" name="req_photo">
                    <label class="custom-control-label" for="id_req_photo">Ответ должен содержать с фотографиям</label>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="form-group">
                <div class="custom-control custom-switch custom-control-inline">
                    <input type="checkbox" class="custom-control-input" id="id_is_required" name="is_required" checked>
                    <label class="custom-control-label" for="id_is_required">Обязательное поле</label>
                </div>
            </div>
        </div>
    </div>
    <div style="text-align: center;">
        <button type="submit" class="btn btn-primary">Создать</button>
    </div>
</form>

{% endblock %}

app/templates/question/update_question.html
{% extends 'layout/basic.html' %}

{% load static %}

{% block title %}
Добавить вопрос
{% endblock %}

{% block main %}

<form method = "post" enctype="multipart/form-data">

    {% csrf_token %}
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label for="id_questionuz">Вопрос на Узбекском</label>
                <textarea required class="form-control" id="id_questionuz" name="questionuz" rows="3" style="width: 700px;">{{ object.questionuz }}</textarea>
            </div>
        </div>    
        <div class="col">
            <div class="form-group">
                <label for="id_questionru">Вопрос на Русском</label>
                <textarea required class="form-control" id="id_questionru" name="questionru" rows="3" style="width: 700px;">{{ object.questionru }}</textarea>
            </div>
        </div>    

    </div>
    <div class="row">

        <div class="col">
            <div class="form-group">
                <label for="id_variantsuz">Варианты на Узбекском</label>
                {% if object.variantsru == None %}
                <input value="" type="text" id="id_variantsuz" name="variantsuz" class="form-control" placeholder="variant1//variants2//variant3">
                {% else %}
                <input value="{{ object.variantsuz }}" type="text" id="id_variantsuz" name="variantsuz" class="form-control" placeholder="variant1//variants2//variant3">
                {% endif %}
            </div>
        </div>

        <div class="col">
            <div class="form-group">
                <label for="id_variantsru">Варианты на Русском</label>
                {% if object.variantsru == None %}
                <input value="" type="text" id="id_variantsru" name="variantsru" class="form-control" placeholder="variant1//variants2//variant3">
                {% else %}
                <input value="{{ object.variantsru }}" type="text" id="id_variantsru" name="variantsru" class="form-control" placeholder="variant1//variants2//variant3">
                {% endif %}
            </div>
        </div>
        
    </div>

    <div class="row">
        <div class="col">
            <div class="form-group">
                <label for="id_index">Индекс</label>
                <input value="{{ object.index }}" type="number" name="index" class="form-control form-control-sm" id="id_index" placeholder="порядок">
            
            </div>
        </div>
        <div class="col">
            <div class="form-group">

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <div class="custom-control custom-switch custom-control-inline">
                    {% if object.req_photo == True %}
                    <input type="checkbox" class="custom-control-input" id="id_req_photo" name="req_photo" checked>
                    {% else %}
                    <input type="checkbox" class="custom-control-input" id="id_req_photo" name="req_photo">
                    {% endif %}
                    <label class="custom-control-label" for="id_req_photo">Ответ должен содержать с фотографиям</label>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="form-group">
                <div class="custom-control custom-switch custom-control-inline">
                    {% if object.is_required == True %}
                    <input type="checkbox" class="custom-control-input" id="id_is_required" name="is_required" checked>
                    {% else %}
                    <input type="checkbox" class="custom-control-input" id="id_is_required" name="is_required">
                    {% endif %}
                    <label class="custom-control-label" for="id_is_required">Обязательное поле</label>
                </div>
            </div>
        </div>
    </div>
    <div style="text-align: center;">
        <button type="submit" class="btn btn-primary">Изменить</button>
    </div>
</form>

{% endblock %}